apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: dev-tools
  namespace: dev-tools
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: dev-tools
  namespace: dev-tools
spec:
  source:
    git:
      uri: https://github.com/eclipse-che-demo-app/che-demo-app.git
      ref: main
    contextDir: "dev-tools"
  strategy:
    dockerStrategy:
      dockerfilePath: "./dev-tools.Containerfile"
  output:
    to:
      kind: ImageStreamTag
      name: dev-tools:latest
